name: Build Assets

on:
  workflow_call:
    inputs:
      branch_ref:
        description: "Branch name to build assets for."
        required: true
        type: string
      node_version:
        description: "Node version to use for the build process."
        required: true
        type: string
      artifact_name:
        description: "Name of the assets artifact."
        required: true
        type: string

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    name: Build Artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_ref }}
          path: ./

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Run npm install and build
        working-directory: ./
        shell: bash
        run: |
          npm ci          
          npm run build
      
      - name: Create SRI JSON
        uses: ./.github/actions/create-sri-json
        with:
          directory: ./dist/bundles/

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./dist/bundles/
