name: "Deploy Branch"

on:
  # push:
  #   branches:
  #     - "**"
  #     - "!beta.release"
  #     - "!main"

  workflow_dispatch:
    inputs:
      node_version:
        description: "Node version to use for the build process."
        default: "latest"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          path: ./${{ github.event.repository.name }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: "npm"
          cache-dependency-path: ./${{ github.event.repository.name }}/package-lock.json
      - name: Run npm install and build
        working-directory: ./${{ github.event.repository.name }}
        shell: bash
        run: |
          npm ci          
          npm run build
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-assets
          path: ./${{ github.event.repository.name }}/dist/bundles/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: built-assets
      - run: ls
